baseurl = "https://Spirit-of-Duthie.github.io/public"
title = "Duthie Day - 10 Dec 2021"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "blue"
  description = "There is a fracture. I need to fix it."
  copyright = "&copy;2021 OxBone"
  sidebarAbout = [
    "Every year, Oxford orthpaedic registrars organise a conference to showcase the local academic and clinical work, and hear from international speakers. The day is named after Robert Duthie, who made great contributions to training and research in Oxford."
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  #email = "oxbone.org@gmail.com"

    # Optional Matomo analytics (formerly piwik)
      # [params.analytics.matomo]
      #  URL = "https://stats.example.com"
      #  ID = "42"
      #  # Track all subdomains with "*.example.com" (Optional)
      #  domain = "www.example.com"
      #  # Optional integrity check hash
      #  hash = ""

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Programme"
  url = "programme/"
  home = true

  [[params.navlinks]]
  name = "About Duthie"
  url = "about/"

  #[[params.navlinks]]
  #name = "Book, Submit, Vote"
  #url = "contact/"

  [[params.navlinks]]
  name = "Book, Submit, Vote"
  url = "contact/"

  [params.social]
  #facebook      = "full page or profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  email         = "oxbone.org@gmail.com"
  twitter       = "https://twitter.com/oxboneorg"
  #linkedin      = "full profile url in linkedin"
  #stackoverflow = "full profile url in stackoverflow"
  #instagram     = "full profile url in instagram"
  github        = "https://github.com/Spirit-of-Duthie"
  #youtube       = "full profile url in youtube"
  #whatsapp      = "wa.me service link"
